name: Ehrengames-Perks
version: '${project.version}'
main: tech.itexpress.perks.loader
api-version: 1.19
author: Lukas Richter
description: Ein Plugin für Ehrengames, das ein Perks-System hinzufügt.

commands:
  perks:
    description: Zeigt alle verfügbaren Perks an.


