name: Ehrengames-Perks
version: '1.0-SNAPSHOT'
main: tech.itexpress.perks.Ehrengames_Perks
api-version: 1.19
author: Ihr Name
description: Ein Plugin für Ehrengames, das ein Perks-System hinzufügt.

commands:
  perks:
    description: Zeigt alle verfügbaren Perks an.
    usage: /perks

